[connections.my_example_connection]
account = "OFIQMBY-FR48453"
user = "KSDAMARLA"
password="Havish415!"
authenticator = "externalbrowser"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive=true
