[connections.snowflake]
account = "OFIQMBY-FR48453"
user = "damarla9861"
password="Havishgayatri415"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive=true
